$:
  push:
    # 导入密钥仓库文件为环境变量
    - imports:
        - https://cnb.cool/tencent/tdesign/tdesign-private/-/blob/main/cnb-envs.yml
      stages:
        - name: sync to github with rebase
          image: tencentcom/git-sync
          settings:
            target_url: https://github.com/TDesignOteam/tdesign-api.git
            auth_type: https
            username: ${GIT_USERNAME}
            password: ${GIT_ACCESS_TOKEN}

  vscode:
    - docker:
        build: .cnb/Dockerfile
        volumes:
          - node_modules:cow
      env:
        CNB_WELCOME_CMD: pnpm dev
      services:
        - vscode
        - docker
      stages:
        - name: install dependencies
          script: 
          - pnpm install 
  
