/* eslint-disable @typescript-eslint/no-unused-vars */
/**
 * 该文件由脚本自动生成，如需修改请联系 PMC
 * This file generated by scripts of tdesign-api. `npm run api:docs Upload React(PC) vitest,finalProject`
 * If you need to modify this file, contact PMC first please.
 */
import React from 'react';
import { fireEvent, vi, render, mockDelay, simulateFileChange } from '@test/utils';
import { Upload } from '..';

describe('Upload Component', () => {
  it('props.accept works fine', () => {
    const wrapper = render(<Upload accept="image/*"></Upload>);
    const container = wrapper.container.querySelector('input');
    expect(container.getAttribute('accept')).toBe('image/*');
  });

  it('props.action works fine', async () => {
    const onSelectChangeFn = vi.fn();
    const onChangeFn = vi.fn();
    const { container } = render(
      <Upload
        action="./request/file-upload-success.json"
        onSelectChange={onSelectChangeFn}
        onChange={onChangeFn}
      ></Upload>,
    );
    const inputDom = container.querySelector('input');
    simulateFileChange(inputDom);
    await mockDelay(300);
    expect(onSelectChangeFn).toHaveBeenCalled();
    expect(onChangeFn).toHaveBeenCalled();
  });

  it('props.disabled: disabled upload can not trigger onSelectChange', () => {
    const onSelectChangeFn = vi.fn();
    const { container } = render(
      <Upload disabled={true} action="./request/file-upload-success.json" onSelectChange={onSelectChangeFn}></Upload>,
    );
    const inputDom = container.querySelector('input');
    simulateFileChange(inputDom);
    expect(onSelectChangeFn).not.toHaveBeenCalled();
  });
});
