name: Auto tdesign-mobile-vue PR

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
    paths:
      - "packages/products/tdesign-mobile-vue/**"
jobs:
  auto-push:
    runs-on: ubuntu-latest
    if: >
      github.event_name == 'pull_request' &&
      github.event.pull_request.merged == false
    steps:
      - run: echo "Clone tdesign-mobile-vue"
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: Tencent/tdesign-mobile-vue
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: target-repo
      - name: Get current time
        run: |
          echo "NOW=$(date +'%Y-%m-%d-%H_%M_%S')" >> $GITHUB_ENV
      - run: |
          cp -rf packages/products/tdesign-mobile-vue/* target-repo/
          cd target-repo/
          git status
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b feat/API-modify-${{ env.NOW }}
          git add .
          git commit -m "feat: modify API"
          git push --set-upstream origin feat/API-modify-${{ env.NOW }}

