name: pr-spell-check
on: [pull_request]

jobs:
    run:
        uses: TDesignOteam/workflows/.github/workflows/reusable-spell-check.yml@86860a363fd94437a642fc968ca220efaa1babfe # main
        with:
            config: .github/workflows/typos-config.toml
