name: pr-spell-check
on: [pull_request]

jobs:
    run:
        uses: TDesignOteam/workflows/.github/workflows/reusable-spell-check.yml@a213a7f227b679c23c639d73b2ca0251023d926f # main
        with:
            config: .github/workflows/typos-config.toml
