name: sync-to-cnb
on:
    - push
    - delete

jobs:
    call-cnb-sync:
        uses: TDesignOteam/workflows/.github/workflows/reusable-cnb-sync.yml@2c83bb5eec2aa598759e8ce57f0af326ed022056 # main
        with:
            github-repo: TDesignOteam/tdesign-api
            cnb-repo: tencent/tdesign/tdesign-api
        secrets:
            CNB_TOKEN: ${{ secrets.CNB_TOKEN }}
